config/routes.rb
PostitTemplate::Application.routes.draw do

  resources :categories

  resources :posts do
    resources :comments
    resources :votes, only: :create
  end

	
  resources :users	

  get "/sign_in", to: "sessions#new"
  post "/sign_in", to: "sessions#create"
  delete "/sign_out", to: "sessions#destroy"

  root to: 'posts#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :tags
  has_many :posts

  validates :name, presence: true, uniqueness: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include Voteable

  belongs_to :post
  belongs_to :user

  has_many :votes, as: :votable

  validates :body, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  include Voteable

  belongs_to :category
  belongs_to :user

  has_many :comments
  has_many :votes, as: :votable

  validates :title, presence: true
  validates :url, presence: true
  validates :category_id, presence: true

  after_validation :generate_slug

  def generate_slug
    proto_slug = normalize_string

    unless self.class.where(slug: proto_slug) == [self]
      self.slug = proto_slug + "-" + SecureRandom.hex
    end
  end

  def normalize_character(i)
    case i
    when /[A-Z]/ then i.downcase
    when /[a-z]/ then i
    when /[0-9]/ then i
    when "-"     then i
    when "_"     then i
    when " "     then "-"
    else              ""
    end
  end

  def normalize_string
    title_as_array  = self.title.split("")
    title_as_array.map! { |i| normalize_character(i) }
    title_as_string = title_as_array.join
    beg_ltr_or_num  = title_as_string.gsub(/\A[^(a-z|\d)]+/, "")
    end_ltr_or_num  = beg_ltr_or_num.gsub(/[^(a-z|\d]+\z/, "")
    single_dashes   = end_ltr_or_num.gsub(/-+/, "-")
  end
end

app/models/user.rb
require "bcrypt"

class User < ActiveRecord::Base
  has_many :comments
  has_many :posts
  has_many :votes

  has_secure_password

	validates :password, length: { minimum: 8 }
  validates :username, presence: true, uniqueness: true
end

app/models/vote.rb
class Vote < ActiveRecord::Base
	belongs_to :votable, polymorphic: true
	belongs_to :user

	validates :value, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def authorize
  	redirect_to sign_in_path, alert: "You must be logged in" if current_user.nil?
  end

  def current_user
    if User.exists? session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      session[:user_id] = nil
    end
  end

  helper_method :current_user
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :authorize

  before_action :set_category, only: [:edit ,:update]

  def create
    @category = Category.new(params_category)

    if @category.save
      redirect_to categories_path
    else
      render "new"
    end
  end

  def edit
  end

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def update
    if @category.update_attributes(params_category)
      redirect_to categories_path
    else
      render "edit"
    end
  end

private

  def params_category
    params[:category].permit(:name)
  end

  def set_category
    @category = Category.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authorize

  def create
    @post     = Post.find(params[:post_id])
    @comment  = Comment.new(comment_params)
    @comments = @post.comments # requires for "posts/show"
    @comment.post = @post
    @comment.user = current_user

    if @comment.save
      redirect_to post_path(@post)
    else
      render "posts/show"
    end
  end

private

  def comment_params
    comment_params = params[:comment].permit(:body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authorize, except: [:index, :show]

  before_action :set_post, only: [:edit, :show, :update]

  def create
    @post = Post.new(params_post)
    @post.user = current_user

    if @post.save
      redirect_to post_path(@path), notice: "Post created successfully"
    else
      render "new"
    end
  end

  def edit
  end

  def index
    @posts = Post.all.sort_by { |i| i.score }.reverse
  end

  def new
    @post = Post.new
    @categories = Category.all
  end

  def show
    @category = @post.category
    @comment  = Comment.new
    @comments = @post.comments
  end

  def update
    if @post.update_attributes(params_post)
      redirect_to @post, notice: "Post updated sucessfully"
    else
      render "edit"
    end
  end

private

  def set_post
    @post = Post.find(params[:id])
  end

  def params_post
    params[:post].permit(:title, :url, :category_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(username: params[:username])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Session created successfully"
    else
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Session destroyed successfully"
  end

  def new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authorize, only: :show

  def create
    @user = User.new(params_user)

    if @user.save
      redirect_to sign_in_path, notice: "User created successfully"
    else
      render "new"
    end
  end

  def new
    @user = User.new
  end

  def show
    @user = current_user
    @posts = @user.posts
    @comments = @user.comments
  end

private

  def params_user
    params[:user].permit(:password, :password_confirmation, :username)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
	before_filter :authorize

  def create
    @vote = find_or_initialize_vote

		case
    when identical? then @vote.destroy
    when opposite?  then @vote.update_attributes(value: params[:value])
    else
      @vote.value = params[:value]
      @vote.save
    end

    respond_to do |format|
      format.html { redirect_to :back }
      format.json { render json: @voteable.score } # score is an integer
    end
	end

private

  def find_or_initialize_vote
    Vote.find_or_initialize_by(votable: set_votable, user_id: current_user.id)
  end

  def identical?
    @vote.value == params[:value].to_i
  end

  def opposite?
    @vote.value == params[:value].to_i * -1
  end

  def set_votable
    if params.has_key? :post_id
      @voteable = Post.find(params[:post_id])
    elsif params.has_key? :comment_id
      @voteable = Comment.find(params[:comment_id])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_form.html.erb
<%= form_for @category do |i| %>
  <% if @category.errors.any? %>
    <p>
      <%= pluralize(@category.errors.count, "error") %>
      prohibited this post from being saved:
    </p>

    <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li>
          <%= msg %>
        </li>
      <% end %>
    </ul>
  <% end %>

  <p>
    <%= i.label :name %>
    <%= i.text_field :name %>
  </p>

  <p>
    <%= i.submit "Submit" %>
  </p>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit Category</h1>

<%= render "form" %>

app/views/categories/index.html.erb
<h1>Categories</h1>

<%= link_to "New Category", new_category_path %>

<ul>
  <% @categories.each do |category| %>
    <li>
      <%= category.name %>
      <%= link_to "Edit", edit_category_path(category) %>
    </li>
  <% end %>
</ul>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render "form" %>

app/views/comments/_form.html.erb
<%= form_for [@post, @comment] do |i| %>
  <% if @comment.errors.any? %>
    <p>
      <%= pluralize(@comment.errors.count, "error") %>
      prohibited this post from being saved:
    </p>

    <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li>
          <%= msg %>
        </li>
      <% end %>
    </ul>
  <% end %>

  <p>
    <%= i.text_field :body %>
    <%= i.submit "Add Comment" %>
  </p>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "Postit!", root_path, :class => 'brand' %>
  </li>
  
  <% unless current_user %>
    <li>
      <%= link_to "Sign Up", new_user_path %>
    </li>

    <li>
      <%= link_to "Sign In", sign_in_path %>
    </li>
  <% end %>

  <% if current_user %>
    <li>
      <%= link_to "New Post", new_post_path %>
    </li>

    <li>
      <%= link_to "My Account", user_path(current_user) %>
    </li>

    <li>
      <%= link_to "Sign Out", sign_out_path, method: :delete %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tealeaf Academy - Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/posts/_errors.html.erb
<% if @post.errors.any? %>
  <p>
    <%= pluralize(@post.errors.count, "error") %>
    prohibited this post from being saved:
  </p>

  <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li>
        <%= msg %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/posts/_form.html.erb
<%= form_for @post do |i| %>
  <%= render "errors" %>

  <p>
    <%= i.label :title %>
    <%= i.text_field :title %>
  </p>

  <p>
    <%= i.label :url %>
    <%= i.text_field :url %>
  </p>

  <p>
    <%= i.label :category_id, "Pick a category" %>
    <%= i.hidden_field :category_id %>
    <input type="text" value="jimmy" id="post_category" />
    <br />
    Choices:
    <% @categories.each do |category| %>
    <%= link_to category.name, "", class: "category", data: { :"category-id" =>category.id } %>
    <% end %>
  </p>

  <p>
    <%= i.submit "Submit" %>
  </p>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render "form" %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<ul>
  <% @posts.each do |post| %>
    <li class="voteable">
    	<%= link_to "", post_votes_path(post, value: 1), class: "icon-chevron-up upvote" %>
      <br />
      <span class="score">
        <%= post.score %>
      </span>
      <br />
      <%= link_to "", post_votes_path(post, value: -1), class: "downvote icon-chevron-down" %>
      <br />
      <%= link_to post.title, "#{post.url}" %>
      <br />
      <%= link_to "#{pluralize(post.comments.count, "comment")}", post_path(post) %>
    </li>
  <% end %>
</ul>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render "form" %>

app/views/posts/show.html.erb
<%= link_to "Edit", edit_post_path(@post) %>

<p>
  <%= @category.name %>
</p>

<p class="voteable">
  <%= link_to "", post_votes_path(@post, value: 1), class: "icon-chevron-up upvote" %>
   <span class="score">
    <%= @post.score %>
  </span>
  <%= link_to "", post_votes_path(@post, value: -1), class: "downvote icon-chevron-down" %>
  <%= link_to @post.title, @post.url %>
  <br />
  <%= link_to "#{pluralize(@post.comments.count, "comment")}", post_path(@post) %>
</p>

<%= render "comments/form" %>

<ul>
  <% @comments.each do |comment| %>
    <li class="voteable">
      <%= link_to "", post_votes_path(comment, value: 1), class: "icon-chevron-up upvote" %>
      <span class="score">
        <%= @post.score %>
      </span>
      <%= link_to "", post_votes_path(comment, value: -1), class: "downvote icon-chevron-down" %>
      <%= comment.body %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>New User</h1>

<%= form_for @user do |i| %>
  <% if @user.errors.any? %>
    <p>
      <%= pluralize(@user.errors.count, "error") %>
      prohibited this post from being saved:
    </p>

    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li>
          <%= msg %>
        </li>
      <% end %>
    </ul>
  <% end %>

  <p>
    <%= i.label :username %>
    <%= i.text_field :username %>
  </p>

  <p>
    <%= i.label :password %>
    <%= i.password_field :password %>
  </p>

  <p>
    <%= i.label :password_confirmation %>
    <%= i.password_field :password_confirmation %>
  </p>

  <p>
    <%= i.submit "Submit" %>
  </p>
<% end %>

app/views/users/show.html.erb
<h1>User</h1>

<% unless @posts.empty? %>
	Posts:
	<ul>
	  <% @posts.each do |post| %>
	    <li>
	      <%= link_to post.title, "#{post.url}" %>
	      <%= link_to "#{pluralize(post.comments.count, "comment")}", post_path(post) %>
	      <%= link_to "edit", edit_post_path(post) %>
	    </li>
	  <% end %>
	</ul>
<% end %>

<% unless @comments.empty? %>
	Comments:
	<ul>
	  <% @comments.each do |comment| %>
	    <li>
	      <%= comment.body %><br />
	      (made on post <%= link_to comment.post.title, post_path(comment.post) %>)
	    </li>
	  <% end %>
	</ul>
<% end %>

<% unless @comments.empty? %>
	Comments:
	<ul>
	  <% @comments.each do |comment| %>
	    <li>
	      <%= comment.body %><br />
	      (made on post <%= link_to comment.post.title, post_path(comment.post) %>)
	    </li>
	  <% end %>
	</ul>
<% end %>